# Generated by Django 3.2.2 on 2021-05-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
